# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_auto_20171124_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsehighlight',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
