# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_responsehighlight_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsehighlight',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 10, 47, 52, 387084)),
        ),
    ]
