# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_auto_20171124_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('video_id', 'pointed_time')},
        ),
        migrations.AlterField(
            model_name='response',
            name='video_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsehighlight',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 11, 39, 30, 586497)),
        ),
        migrations.AlterField(
            model_name='responsehighlight',
            name='video_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
